фон в зависимости от ширины
js-tasks-ru/htmlcss-20220919_mariya71 pull request #14
Opened 2022-10-12 10:57 UTC by frolictc

2022-10-12 10:58 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-12 20:37 UTC, GSemikozov requested changes

2022-10-12 20:37 UTC, GSemikozov commented on 06-lection4/02-background-image/background-image.css
> +@media screen and (max-width: 400px)  {
если desktop first, то тогда от бОльше го к меньшему (меняем порядок медиа-запросов), + используем только max-width

2022-10-13 07:43 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-13 18:56 UTC, GSemikozov approved these changes

2022-10-13 18:56 UTC, merged