radio
js-tasks-ru/htmlcss-20220919_mariya71 pull request #19
Opened 2022-10-17 12:03 UTC by frolictc

2022-10-17 12:04 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-18 08:55 UTC, GSemikozov requested changes

2022-10-18 08:55 UTC, GSemikozov commented on 07-lection5/02-radio/radio.css
> +    position: relative;
display: inline-block

2022-10-18 19:49 UTC, GSemikozov approved these changes

2022-10-18 19:49 UTC, merged