меню табуляция
js-tasks-ru/htmlcss-20220919_mariya71 pull request #22
Opened 2022-10-17 17:21 UTC by frolictc

2022-10-17 17:22 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-18 09:01 UTC, GSemikozov requested changes

2022-10-18 09:01 UTC, GSemikozov commented on components/tabs/tabs.css
> +.header:has(.tabs__radio:checked) ~ .preview .preview__item {
через heder не надо работать, мы должны описывать логику только на основании элементов блока. Табы - это на самом деле не часть хедера, это блок под хедером, который включает в себя превью. Организовать можно например так: .tabs__radio_all:checked ~ .tabs__section_all { display: block } а по умолчанию .tabs__section  { display: none }

2022-10-18 13:00 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-18 13:01 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-18 13:10 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-18 19:52 UTC, GSemikozov requested changes

2022-10-18 19:52 UTC, GSemikozov commented on components/tabs/tabs.css
> +#tab1:checked ~ .preview .tabs__item {
#tab1:checked ~ .tabs__preview .tabs__item

2022-10-18 19:52 UTC, GSemikozov commented on components/tabs/tabs.css
> +#tab1:checked ~ .preview .tabs__item {
хотя бы так

2022-10-19 10:08 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-19 10:10 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-20 08:01 UTC, GSemikozov approved these changes

2022-10-20 08:01 UTC, merged