Блок кнопки
js-tasks-ru/htmlcss-20220919_mariya71 pull request #3
Opened 2022-09-24 17:36 UTC by frolictc

2022-09-24 17:37 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-09-26 08:07 UTC, GSemikozov requested changes

2022-09-26 08:07 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    min-width: 182px;
вот это не обязательно, но можно и оставить, а вот чего не хватает - так это padding

2022-09-26 08:07 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button-primary {
модификаторы пишем через 1 нижнее подчеркивание (поправить везде)

2022-09-26 16:18 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-09-27 08:25 UTC, GSemikozov requested changes

2022-09-27 08:25 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    padding: 15px 14px;
чтобы высота кнопки соответствовала макету нужно снизу 14px - padding: 15px 15px 14px;

2022-09-28 16:59 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-09-28 21:24 UTC, GSemikozov approved these changes

2022-09-28 21:24 UTC, merged