Main page
js-tasks-ru/htmlcss-20220919_mariya71 pull request #4
Opened 2022-09-28 17:47 UTC by frolictc

чтобы сделать отступы между карточками использовала модификатор, не думаю что это правильно, ведь карточек может быть любое количество, но другого решения не придумала. хотела бы получить совет/подсказку

2022-09-28 17:48 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-09-28 21:27 UTC, GSemikozov requested changes

2022-09-28 21:27 UTC, GSemikozov commented on components/footer/footer.css
> +    max-width: 640px;
и тогда margin: 0 auto

2022-09-28 21:27 UTC, GSemikozov commented on components/footer/footer.css
> +    padding-bottom: 32px;
внешний отступ, поэтому margin-bottom

2022-10-05 06:08 UTC, GSemikozov approved these changes

2022-10-05 06:09 UTC, GSemikozov approved these changes

2022-10-05 06:14 UTC, GSemikozov approved these changes

2022-10-05 06:15 UTC, merged

2022-10-05 06:17 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2022-10-05 06:23 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.