Аккордеон
js-tasks-ru/htmlcss-20220919_mariya71 pull request #5
Opened 2022-09-28 18:47 UTC by frolictc

2022-09-28 18:47 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-09-28 18:55 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-09-28 21:30 UTC, GSemikozov requested changes

2022-09-28 21:30 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    border-radius: 8px;
вот здесь лучше указать общие паддинги, вместо того чтобы задавать однотипные отступы у .accordion__summary и .accordion__item

2022-09-28 21:30 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion__details > .accordion__summary::-webkit-details-marker {
лишняя вложенность, можно просто .accordion__summary::-webkit-details-marker

2022-09-28 21:30 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion__details > .accordion__summary {
и тут

2022-09-28 21:30 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion__details > .accordion__summary:after {
и тут

2022-09-28 21:30 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion__details[open] > .accordion__summary:after {
это лишнее (дублирует то что выше)

2022-09-28 21:30 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    padding: 24px 0 24px 32px;
по отступам см коммент выше

2022-09-28 21:30 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    padding: 0 49px 16px 32px;
и тут

2022-09-28 21:30 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +            <p class="accordion__item">
по смыслу это все-таки не айтем, это контент, то есть accordion__content

2022-09-29 15:52 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-09-29 20:40 UTC, GSemikozov requested changes

2022-09-29 20:40 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    padding: 24px 0 24px 32px;
справа все-таки тоже нужен

2022-09-29 20:40 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    max-width: 650px;
лишнее ограничение

2022-09-29 20:40 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    padding: 24px 0 24px 32px;
и когда .accordion__details[open] - паддинг снизу другой)

2022-09-29 20:40 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    max-width: 650px;
и по идее должен быть отступ сверху от заголовка?)

2022-10-03 13:53 UTC, frolictc commented on 03-lection1/02-accordion/accordion.css
> +.accordion__details[open] > .accordion__summary:after {
не понимаю в чем дублирование

2022-10-03 14:05 UTC, frolictc commented on 03-lection1/02-accordion/accordion.css
> +    padding-top: 16px;
так можно?

2022-10-03 19:52 UTC, GSemikozov approved these changes

2022-10-03 19:52 UTC, merged