гистограмма
js-tasks-ru/htmlcss-20220919_mariya71 pull request #6
Opened 2022-09-30 06:15 UTC by frolictc

2022-09-30 06:15 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-03 14:05 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-03 14:43 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-03 14:58 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-03 19:50 UTC, GSemikozov requested changes

2022-10-03 19:50 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    float: right;
про флоаты забываем, надо применять флексы

2022-10-03 19:50 UTC, GSemikozov commented on 04-lection2/01-histogram/index.html
> +                    <p class="histogram__text histogram__text_link">View all</p>
если это ссылка, то тогда тег `<a>`; по структуре - должна быть на одном уровне с histogram__text_title

2022-10-03 19:50 UTC, GSemikozov commented on 04-lection2/01-histogram/index.html
> +                            <div class="chart__item" style="height: 50px">
лишний враппер, можно сразу chart__el

2022-10-03 19:50 UTC, GSemikozov commented on 04-lection2/01-histogram/chart.css
> +    height: 100%;
лишнее; здесь договаривались зафиксировать - 50px (чтобы дочерним элементам задавать высоту в процентах относительно этой высоты)

2022-10-03 19:50 UTC, GSemikozov commented on 04-lection2/01-histogram/chart.css
> +    min-width: 9px;
flex-basis

2022-10-03 19:50 UTC, GSemikozov commented on 04-lection2/01-histogram/chart.css
> +    height: 100%;
удалим (если с сервера придет null, а мы покажем 100% - то это будет обман пользователя)

2022-10-03 19:50 UTC, GSemikozov commented on 04-lection2/01-histogram/chart.css
> +.chart__item {
этот лишний враппер удалим, а отступ на уровне родителя (.chart) зададим через gap

2022-10-03 19:50 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    max-width: 200px;
лишнее ограничение

2022-10-03 19:50 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    margin-top: 71px;
точно ли должен быть такой большой отступ?

2022-10-04 03:18 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-05 06:09 UTC, GSemikozov requested changes

2022-10-05 06:09 UTC, GSemikozov commented on 04-lection2/01-histogram/chart.css
> +    justify-content: space-around;
лишнее

2022-10-05 06:09 UTC, GSemikozov commented on 04-lection2/01-histogram/chart.css
> +    flex-basis: 8px;
9 (не придираюсь =))

2022-10-06 20:06 UTC, GSemikozov submitted a review, later dismissed

2022-10-07 05:09 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-07 15:53 UTC, GSemikozov approved these changes

2022-10-07 15:53 UTC, merged